/*
 * autogenerated-element-type.c - element-name -> element_type lookup.
 *
 * UPSTREAM NOTE: In stock libhubbub this file is produced by `gperf` from
 * treebuilder/element-type.gperf (a perfect hash). gperf was not available in
 * the Positron build environment (VS2008 / WinCE toolchain), so this is a
 * hand-written, interface-compatible replacement.
 *
 * It is #included by treebuilder/element-type.c (NOT compiled on its own),
 * exactly as the gperf output was, and exposes the same function:
 *
 *     const struct element_type_map *hubbub_element_type_generated_lookup(
 *             const char *str, size_t len);
 *
 * Semantics match the gperf options used in element-type.gperf:
 *   %ignore-case        -> ASCII case-insensitive match
 *   %compare-strncmp    -> exact length match (len must equal strlen(name))
 *
 * The table below is a verbatim transcription of element-type.gperf's 106
 * name->type rows (do not add or remove rows: that would change parsing
 * behaviour relative to upstream hubbub). Lookup is linear; with ~106 entries
 * and one call per tag this is negligible next to tokenising/layout, and it is
 * trivially correct. Swap for a binary search (the table is already sorted) if
 * profiling ever shows it hot.
 */

#include <stddef.h>

#include "treebuilder/element-type.h"

/* ASCII-only tolower; locale-independent, safe on WinCE. */
#define POS_EL_TOLOWER(c) \
	(((c) >= 'A' && (c) <= 'Z') ? ((c) + ('a' - 'A')) : (c))

/* Verbatim from element-type.gperf, kept in its original (sorted) order.
 * Named `wordlist` because element-type.c's element_type_to_name() iterates
 * it directly by that name (it was the gperf table's symbol). */
static const struct element_type_map wordlist[] = {
	{ "a",              A },
	{ "address",        ADDRESS },
	{ "annotation-xml", ANNOTATION_XML },
	{ "applet",         APPLET },
	{ "area",           AREA },
	{ "article",        ARTICLE },
	{ "aside",          ASIDE },
	{ "b",              B },
	{ "base",           BASE },
	{ "basefont",       BASEFONT },
	{ "bgsound",        BGSOUND },
	{ "big",            BIG },
	{ "blockquote",     BLOCKQUOTE },
	{ "body",           BODY },
	{ "br",             BR },
	{ "button",         BUTTON },
	{ "caption",        CAPTION },
	{ "center",         CENTER },
	{ "col",            COL },
	{ "colgroup",       COLGROUP },
	{ "command",        COMMAND },
	{ "dd",             DD },
	{ "desc",           DESC },
	{ "details",        DETAILS },
	{ "dialog",         DIALOG },
	{ "dir",            DIR },
	{ "div",            DIV },
	{ "dl",             DL },
	{ "dt",             DT },
	{ "em",             EM },
	{ "embed",          EMBED },
	{ "fieldset",       FIELDSET },
	{ "figcaption",     FIGCAPTION },
	{ "figure",         FIGURE },
	{ "font",           FONT },
	{ "footer",         FOOTER },
	{ "foreignobject",  FOREIGNOBJECT },
	{ "form",           FORM },
	{ "frame",          FRAME },
	{ "frameset",       FRAMESET },
	{ "h1",             H1 },
	{ "h2",             H2 },
	{ "h3",             H3 },
	{ "h4",             H4 },
	{ "h5",             H5 },
	{ "h6",             H6 },
	{ "head",           HEAD },
	{ "hr",             HR },
	{ "html",           HTML },
	{ "i",              I },
	{ "iframe",         IFRAME },
	{ "image",          IMAGE },
	{ "img",            IMG },
	{ "input",          INPUT },
	{ "isindex",        ISINDEX },
	{ "li",             LI },
	{ "link",           LINK },
	{ "listing",        LISTING },
	{ "malignmark",     MALIGNMARK },
	{ "marquee",        MARQUEE },
	{ "math",           MATH },
	{ "menu",           MENU },
	{ "meta",           META },
	{ "mglyph",         MGLYPH },
	{ "mi",             MI },
	{ "mn",             MN },
	{ "mo",             MO },
	{ "ms",             MS },
	{ "mtext",          MTEXT },
	{ "nobr",           NOBR },
	{ "noembed",        NOEMBED },
	{ "noframes",       NOFRAMES },
	{ "noscript",       NOSCRIPT },
	{ "object",         OBJECT },
	{ "ol",             OL },
	{ "optgroup",       OPTGROUP },
	{ "option",         OPTION },
	{ "output",         OUTPUT },
	{ "p",              P },
	{ "param",          PARAM },
	{ "plaintext",      PLAINTEXT },
	{ "pre",            PRE },
	{ "s",              S },
	{ "script",         SCRIPT },
	{ "select",         SELECT },
	{ "small",          SMALL },
	{ "spacer",         SPACER },
	{ "strike",         STRIKE },
	{ "strong",         STRONG },
	{ "style",          STYLE },
	{ "summary",        SUMMARY },
	{ "svg",            SVG },
	{ "table",          TABLE },
	{ "tbody",          TBODY },
	{ "td",             TD },
	{ "textarea",       TEXTAREA },
	{ "tfoot",          TFOOT },
	{ "th",             TH },
	{ "thead",          THEAD },
	{ "title",          TITLE },
	{ "tr",             TR },
	{ "tt",             TT },
	{ "u",              U },
	{ "ul",             UL },
	{ "wbr",            WBR },
	{ "xmp",            XMP }
};

#define POS_EL_COUNT \
	(sizeof(wordlist) / sizeof(wordlist[0]))

const struct element_type_map *hubbub_element_type_generated_lookup(
		const char *str, size_t len)
{
	size_t i;

	for (i = 0; i < POS_EL_COUNT; i++) {
		const char *name = wordlist[i].name;
		size_t j = 0;

		while (j < len && name[j] != '\0' &&
				POS_EL_TOLOWER((unsigned char) str[j]) ==
					(unsigned char) name[j]) {
			j++;
		}

		if (j == len && name[j] == '\0') {
			return &wordlist[i];
		}
	}

	return NULL;
}
