#!/usr/bin/env python3
"""
gen_ca_bundle.py - extract a subset of Mozilla roots from curl's
cacert.pem and emit a C header (ca_bundle.h) for embedding into
positron_tls.dll.

We intentionally do NOT ship the full Mozilla bundle (~200 KB+) on a
WM6 device. The 5 roots picked below were chosen by inspecting actual
chains served by our test endpoints (api.ipify.org, httpbin.org,
api.anthropic.com, badssl.com) plus two defensive picks for general
public-web coverage. Re-evaluate when a new target service surfaces.

  - GTS Root R4                          : Google Trust Services
                                           (api.ipify.org,
                                            api.anthropic.com)
  - Amazon Root CA 1                     : AWS-fronted services
                                           (httpbin.org)
  - ISRG Root X1                         : Let's Encrypt
                                           (badssl.com and most
                                            of the small web)
  - DigiCert Global Root G2              : defensive - many SaaS
  - USERTrust RSA Certification Authority: defensive - Sectigo,
                                           common in SMB/internal CAs

To refresh, re-run this script. cacert.pem itself is a periodically
refreshed export of the Mozilla NSS trust store.

Usage:
  python gen_ca_bundle.py
    (downloads cacert.pem from curl.se to memory, regenerates
     ca_bundle.h next to this script)

  python gen_ca_bundle.py path/to/cacert.pem
    (uses a local cacert.pem; useful when offline)
"""

import os
import sys
import urllib.request

WANTED = (
    "GTS Root R4",
    "Amazon Root CA 1",
    "ISRG Root X1",
    "DigiCert Global Root G2",
    "USERTrust RSA Certification Authority",
)

CACERT_URL = "https://curl.se/ca/cacert.pem"


def parse_bundle(text):
    """Yield (friendly_name, pem_block) for each cert in cacert.pem."""
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i].rstrip()
        # Friendly name appears on its own line, followed by ====...
        if (i + 1 < len(lines)
                and lines[i + 1].startswith("===")
                and line
                and not line.startswith("#")):
            name = line
            # Skip the === line.
            j = i + 2
            # Find -----BEGIN CERTIFICATE----- after metadata block.
            while j < len(lines) and not lines[j].startswith("-----BEGIN"):
                j += 1
            start = j
            # Read until -----END CERTIFICATE-----.
            while j < len(lines) and not lines[j].startswith("-----END"):
                j += 1
            if j < len(lines) and lines[j].startswith("-----END"):
                pem = "\n".join(lines[start : j + 1]) + "\n"
                yield name, pem
                i = j + 1
                continue
        i += 1


def fetch_cacert():
    """Download cacert.pem to memory."""
    print(f"Fetching {CACERT_URL} ...", file=sys.stderr)
    with urllib.request.urlopen(CACERT_URL, timeout=30) as resp:
        return resp.read().decode("ascii", errors="replace")


def main():
    if len(sys.argv) > 1:
        with open(sys.argv[1], "r", encoding="ascii", errors="replace") as f:
            text = f.read()
    else:
        text = fetch_cacert()

    found = {}
    for name, pem in parse_bundle(text):
        if name in WANTED and name not in found:
            found[name] = pem

    missing = [n for n in WANTED if n not in found]
    if missing:
        print("ERROR: roots not found in cacert.pem:", file=sys.stderr)
        for n in missing:
            print(f"  - {n}", file=sys.stderr)
        sys.exit(1)

    out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            "ca_bundle.h")
    total_bytes = 0

    with open(out_path, "w", encoding="ascii", newline="\n") as out:
        out.write("/*\n")
        out.write(" * ca_bundle.h - generated by gen_ca_bundle.py.\n")
        out.write(" * Embedded subset of the Mozilla CA trust store,\n")
        out.write(" * just enough roots for everything positron_tls\n")
        out.write(" * is expected to talk to.\n")
        out.write(" *\n")
        out.write(" * DO NOT EDIT BY HAND. Regenerate when roots expire\n")
        out.write(" * or when a new target service uses an unfamiliar CA.\n")
        out.write(" */\n")
        out.write("\n")
        out.write("#ifndef POSITRON_CA_BUNDLE_H\n")
        out.write("#define POSITRON_CA_BUNDLE_H\n")
        out.write("\n")
        out.write("static const char g_ca_bundle_pem[] =\n")

        for name in WANTED:
            pem = found[name]
            out.write(f"    /* {name} */\n")
            for line in pem.splitlines():
                # C string literal, double quotes escaped (PEM has none),
                # backslashes don't occur in base64+headers either.
                out.write(f'    "{line}\\n"\n')
            total_bytes += len(pem) + 1   # newline between blocks

        out.write("    ;\n")
        out.write("\n")
        out.write("/* Size in bytes including trailing NUL. mbedTLS PEM\n")
        out.write(" * parsing requires NUL-terminated input with len\n")
        out.write(" * counting the NUL. */\n")
        out.write("static const unsigned int g_ca_bundle_pem_len =\n")
        out.write("    (unsigned int)sizeof(g_ca_bundle_pem);\n")
        out.write("\n")
        out.write("#endif /* POSITRON_CA_BUNDLE_H */\n")

    print(f"Wrote {out_path}", file=sys.stderr)
    print(f"  {len(found)} certificates, ~{total_bytes} bytes of PEM",
          file=sys.stderr)


if __name__ == "__main__":
    main()
