#!/usr/bin/env python3
"""
gen_ca_bundle.py - embed curl's cacert.pem (the full Mozilla CA trust
store) into a C header (ca_bundle.h) for positron_tls.dll, so the TLS
client can verify arbitrary public HTTPS sites. A real browser ships the
whole root set, not a hand-picked subset; cherry-picking by friendly name
is fragile (names change, roots get removed), which is why we now take
everything.

Each certificate is emitted as its own C string literal in an array
(g_ca_certs[]); positron_tls parses them one-by-one in PTls_Init. We do
NOT concatenate them into one big string: MSVC caps a single (concatenated)
string literal at ~64 KB, and the full bundle is ~220 KB.

Usage:
  python gen_ca_bundle.py
    (downloads cacert.pem from curl.se, regenerates ca_bundle.h)

  python gen_ca_bundle.py path/to/cacert.pem
    (uses a local cacert.pem; useful when the download is blocked)
"""

import os
import sys
import urllib.request

CACERT_URL = "https://curl.se/ca/cacert.pem"


def parse_bundle(text):
    """Yield (friendly_name, pem_block) for each cert in cacert.pem."""
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i].rstrip()
        # Friendly name appears on its own line, followed by ====...
        if (i + 1 < len(lines)
                and lines[i + 1].startswith("===")
                and line
                and not line.startswith("#")):
            name = line
            # Skip the === line, find the BEGIN CERTIFICATE marker.
            j = i + 2
            while j < len(lines) and not lines[j].startswith("-----BEGIN"):
                j += 1
            start = j
            while j < len(lines) and not lines[j].startswith("-----END"):
                j += 1
            if j < len(lines) and lines[j].startswith("-----END"):
                pem = "\n".join(lines[start : j + 1]) + "\n"
                yield name, pem
                i = j + 1
                continue
        i += 1


def fetch_cacert():
    """Download cacert.pem to memory."""
    print(f"Fetching {CACERT_URL} ...", file=sys.stderr)
    with urllib.request.urlopen(CACERT_URL, timeout=30) as resp:
        return resp.read().decode("ascii", errors="replace")


def main():
    if len(sys.argv) > 1:
        with open(sys.argv[1], "r", encoding="ascii", errors="replace") as f:
            text = f.read()
    else:
        text = fetch_cacert()

    certs = list(parse_bundle(text))
    if not certs:
        print("ERROR: no certificates parsed from cacert.pem", file=sys.stderr)
        sys.exit(1)

    out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            "ca_bundle.h")
    total_bytes = 0
    max_literal = 0

    with open(out_path, "w", encoding="ascii", newline="\n") as out:
        out.write("/*\n")
        out.write(" * ca_bundle.h - generated by gen_ca_bundle.py.\n")
        out.write(" * The full Mozilla CA trust store (curl's cacert.pem),\n")
        out.write(" * one C string literal per root, so positron_tls can\n")
        out.write(" * verify arbitrary public HTTPS sites.\n")
        out.write(" *\n")
        out.write(" * DO NOT EDIT BY HAND. Regenerate with gen_ca_bundle.py.\n")
        out.write(" */\n")
        out.write("\n")
        out.write("#ifndef POSITRON_CA_BUNDLE_H\n")
        out.write("#define POSITRON_CA_BUNDLE_H\n")
        out.write("\n")
        out.write("/* One NUL-terminated PEM string per trusted root. */\n")
        out.write("static const char *g_ca_certs[] = {\n")

        for name, pem in certs:
            # Comment is just a label: drop the */ breakout and force ASCII
            # (some friendly names contain non-ASCII; keep ca_bundle.h ASCII).
            safe = name.replace("*/", "* /").encode("ascii", "replace").decode("ascii")
            out.write(f"    /* {safe} */\n")
            for line in pem.splitlines():
                # PEM is base64 + ASCII headers: no '"' or '\' to escape.
                out.write(f'    "{line}\\n"\n')
            out.write("    ,\n")
            total_bytes += len(pem)
            if len(pem) + 1 > max_literal:
                max_literal = len(pem) + 1

        out.write("};\n")
        out.write("\n")
        out.write("static const int g_ca_cert_count =\n")
        out.write("    (int)(sizeof(g_ca_certs) / sizeof(g_ca_certs[0]));\n")
        out.write("\n")
        out.write("#endif /* POSITRON_CA_BUNDLE_H */\n")

    print(f"Wrote {out_path}", file=sys.stderr)
    print(f"  {len(certs)} certificates, ~{total_bytes} bytes of PEM; "
          f"largest single cert ~{max_literal} bytes", file=sys.stderr)
    if max_literal > 60000:
        print("  WARNING: a single cert literal is near MSVC's ~64 KB limit.",
              file=sys.stderr)


if __name__ == "__main__":
    main()
