#!/usr/bin/env python3
"""Build the static WinCE fallback fonts shipped with Positron.

The source fonts stay vendored under third_party so this step is offline and
reproducible.  FontTools turns Noto Emoji's variable font into a regular
static TrueType font before subsetting it; Windows Mobile 6 GDI only sees the
resulting classic glyf/loca/cmap tables.
"""

from pathlib import Path
from fontTools.subset import Options, Subsetter
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "assets" / "fonts"
COVERAGE = ROOT / "positron_core" / "pcore_font_coverage.h"

SYMBOL_SOURCE = (
    ROOT / "third_party" / "noto-symbols2" /
    "NotoSansSymbols2-Regular.ttf"
)
EMOJI_SOURCE = ROOT / "third_party" / "noto-emoji" / "NotoEmoji-wght.ttf"


def codepoints(ranges, singles=()):
    result = set(singles)
    for first, last in ranges:
        result.update(range(first, last + 1))
    return result


SYMBOL_CODEPOINTS = codepoints(
    (
        (0x2190, 0x21FF),  # arrows
        (0x2300, 0x23FF),  # miscellaneous technical
        (0x25A0, 0x27BF),  # geometric shapes, symbols, dingbats
        (0x2B00, 0x2BFF),  # supplemental arrows and symbols
    ),
    (0x2022,),             # NetSurf's disc list marker
)

EMOJI_CODEPOINTS = codepoints(
    (
        (0x2300, 0x23FF),
        (0x25A0, 0x27BF),
        (0x2B00, 0x2BFF),
        (0x1F000, 0x1FAFF),
    ),
    (0x200D, 0x20E3, 0xFE0E, 0xFE0F),
)


def rename_font(font, family, postscript):
    names = font["name"]
    replacements = {
        1: family,
        2: "Regular",
        3: family + " Regular",
        4: family + " Regular",
        6: postscript,
    }
    for record in names.names:
        value = replacements.get(record.nameID)
        if value is not None:
            record.string = value.encode(record.getEncoding(), errors="replace")


def add_bmp_emoji_aliases(font):
    best = font.getBestCmap()
    supplementary = sorted(cp for cp in best if cp > 0xFFFF)
    if len(supplementary) > 0x1900:
        raise RuntimeError("emoji subset no longer fits the BMP private-use area")
    mapping = []
    for index, codepoint in enumerate(supplementary):
        pua = 0xE000 + index
        glyph = best[codepoint]
        for table in font["cmap"].tables:
            if table.isUnicode() and table.format in (4, 12):
                table.cmap[pua] = glyph
        mapping.append((codepoint, pua))
    return mapping


def build_font(source, destination, wanted, family, postscript,
               variable=False, bmp_aliases=False):
    font = TTFont(source)
    if variable:
        font = instantiateVariableFont(
            font, {"wght": 400}, inplace=False, optimize=True
        )

    options = Options()
    options.hinting = True
    options.layout_features = []
    options.name_IDs = [0, 1, 2, 3, 4, 5, 6, 13, 14]
    options.notdef_glyph = True
    options.notdef_outline = True
    options.recalc_bounds = True
    options.recalc_timestamp = False

    subsetter = Subsetter(options=options)
    subsetter.populate(unicodes=wanted)
    subsetter.subset(font)
    rename_font(font, family, postscript)
    aliases = add_bmp_emoji_aliases(font) if bmp_aliases else []
    for table in ("GDEF", "GPOS", "GSUB", "STAT", "vhea", "vmtx"):
        if table in font:
            del font[table]
    font.recalcTimestamp = False
    font["head"].modified = 3660681600  # 2020-01-01, stable reproducible build
    font.save(destination)

    cmap = {
        cp
        for table in font["cmap"].tables
        if table.isUnicode()
        for cp in table.cmap
    }
    return sorted(cmap), aliases


def compact_ranges(points):
    if not points:
        return []
    ranges = []
    first = previous = points[0]
    for point in points[1:]:
        if point != previous + 1:
            ranges.append((first, previous))
            first = point
        previous = point
    ranges.append((first, previous))
    return ranges


def write_range_array(out, name, points):
    ranges = compact_ranges(points)
    out.write("static const pcore_font_range %s[] = {\n" % name)
    for first, last in ranges:
        out.write("    { 0x%08xUL, 0x%08xUL },\n" % (first, last))
    out.write("};\n")
    out.write(
        "#define %s_COUNT (sizeof(%s) / sizeof(%s[0]))\n\n" %
        (name.upper(), name, name)
    )


def write_coverage(symbols, emoji, aliases):
    with COVERAGE.open("w", encoding="ascii", newline="\n") as out:
        out.write("/* Generated by scripts/build_fonts.py. Do not edit. */\n")
        out.write("#ifndef PCORE_FONT_COVERAGE_H\n")
        out.write("#define PCORE_FONT_COVERAGE_H\n\n")
        out.write("typedef struct pcore_font_range {\n")
        out.write("    unsigned long first;\n")
        out.write("    unsigned long last;\n")
        out.write("} pcore_font_range;\n\n")
        write_range_array(out, "pcore_symbol_ranges", symbols)
        write_range_array(out, "pcore_emoji_ranges", emoji)
        out.write("typedef struct pcore_emoji_alias {\n")
        out.write("    unsigned long codepoint;\n")
        out.write("    unsigned short pua;\n")
        out.write("} pcore_emoji_alias;\n\n")
        out.write("static const pcore_emoji_alias pcore_emoji_aliases[] = {\n")
        for codepoint, pua in aliases:
            out.write("    { 0x%08xUL, 0x%04x },\n" % (codepoint, pua))
        out.write("};\n")
        out.write("#define PCORE_EMOJI_ALIASES_COUNT ")
        out.write("(sizeof(pcore_emoji_aliases) / ")
        out.write("sizeof(pcore_emoji_aliases[0]))\n\n")
        out.write("#endif\n")


def main():
    OUTPUT.mkdir(parents=True, exist_ok=True)
    symbols, unused_aliases = build_font(
        SYMBOL_SOURCE,
        OUTPUT / "PositronSymbols.ttf",
        SYMBOL_CODEPOINTS,
        "Positron Symbols",
        "PositronSymbols-Regular",
    )
    emoji, aliases = build_font(
        EMOJI_SOURCE,
        OUTPUT / "PositronEmoji.ttf",
        EMOJI_CODEPOINTS,
        "Positron Emoji",
        "PositronEmoji-Regular",
        variable=True,
        bmp_aliases=True,
    )
    write_coverage(symbols, emoji, aliases)
    print("PositronSymbols.ttf: %d code points" % len(symbols))
    print("PositronEmoji.ttf: %d code points" % len(emoji))


if __name__ == "__main__":
    main()
