#!/usr/bin/env python3
"""Generate libsvgtiny's named-colour lookup without requiring gperf.

The upstream build uses gperf to produce autogenerated_colors.c. VS2008/WM
build machines do not normally have gperf, so this conservative generator
turns the same colors.gperf source into a small C89 linear lookup table.
SVG named colours are few enough that parse-time linear lookup is acceptable;
the source data remains upstream-owned and auditable.
"""

from pathlib import Path
import re
import sys


ENTRY = re.compile(
    r"^([a-z]+),\s*svgtiny_RGB\(\s*(\d+),\s*(\d+),\s*(\d+)\s*\)\s*$")


def main():
    if len(sys.argv) != 3:
        print("usage: gen_svgtiny_colors.py <colors.gperf> <output.c>")
        return 2

    source = Path(sys.argv[1])
    output = Path(sys.argv[2])
    entries = []
    in_words = False

    for line_no, raw in enumerate(source.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if line == "%%":
            in_words = not in_words
            continue
        if not in_words or not line:
            continue
        match = ENTRY.match(line)
        if not match:
            raise SystemExit("%s:%d: unsupported colour entry: %s" %
                             (source, line_no, raw))
        entries.append(match.groups())

    if not entries:
        raise SystemExit("%s: no colour entries found" % source)

    lines = [
        "/* Generated by scripts/gen_svgtiny_colors.py from colors.gperf. */",
        "static const struct svgtiny_named_color svgtiny_color_table[] = {",
    ]
    for name, red, green, blue in entries:
        lines.append('    { "%s", svgtiny_RGB(%s, %s, %s) },' %
                     (name, red, green, blue))
    lines.extend([
        "};",
        "",
        "static const struct svgtiny_named_color *svgtiny_color_lookup(",
        "        const char *name, size_t length)",
        "{",
        "    size_t i;",
        "    size_t count;",
        "",
        "    count = sizeof(svgtiny_color_table) / sizeof(svgtiny_color_table[0]);",
        "    for (i = 0; i < count; i++) {",
        "        const char *candidate;",
        "",
        "        candidate = svgtiny_color_table[i].name;",
        "        if (strlen(candidate) == length &&",
        "                memcmp(candidate, name, length) == 0) {",
        "            return &svgtiny_color_table[i];",
        "        }",
        "    }",
        "    return NULL;",
        "}",
        "",
    ])
    output.write_text("\n".join(lines), encoding="ascii", newline="\n")
    print("gen_svgtiny_colors: wrote %s (%d colours)" % (output, len(entries)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
