#!/usr/bin/perl
#
# scripts/mkparsers.pl - Positron reimplementation of libcss's CSS property
# parser generator (netsurf-all-3.11/libcss/src/parse/properties/
# css_property_parser_gen.c, the host tool the upstream Makefile compiles to
# build/gen_parser).
#
# We have perl but no usable host C compiler on this toolchain (the VS2008
# install used for the WinCE/ARM cross build ships no desktop vcvars), so we
# port the generator to perl instead of compiling and running the C version.
# This is a faithful, line-for-line port of the C source's output_* routines;
# the emitted C is intended to be equivalent to upstream's gen_parser output.
#
# For each non-comment "name:..." line in properties.gen it writes
# <outdir>/autogenerated_<name>.c, exactly as the upstream
# src/parse/properties/Makefile rule does:
#     gen_parser -o autogenerated_$1.c '<the matching properties.gen line>'
#
# Usage: perl mkparsers.pl <path/to/properties.gen> <output-dir>
#
# Upstream is MIT licensed (Copyright 2010 The NetSurf Browser Project);
# the generated files carry that header, matching the C generator.

use strict;
use warnings;

my ($genfile, $outdir) = @ARGV;
die "usage: perl mkparsers.pl <properties.gen> <outdir>\n"
    unless defined $genfile && defined $outdir;

open(my $GEN, '<', $genfile) or die "cannot open $genfile: $!\n";
my $count = 0;
while (my $line = <$GEN>) {
    $line =~ s/\r?\n\z//;            # strip EOL (handle CRLF too)
    next if $line eq '';
    next if $line =~ /^#/;           # comment / template line
    next unless $line =~ /^([A-Za-z_][A-Za-z0-9_]*):/;
    my $name = $1;
    my $text = gen_parser($line);
    my $path = "$outdir/autogenerated_$name.c";
    open(my $O, '>', $path) or die "cannot write $path: $!\n";
    print $O $text;
    close($O);
    $count++;
}
close($GEN);
print "mkparsers: generated $count parser file(s) into $outdir\n";

# ---------------------------------------------------------------------------
# Port of main(): parse the descriptor into keyval lists, then emit the parser.
# ---------------------------------------------------------------------------
sub gen_parser {
    my ($descriptor) = @_;

    my (@base, @IDENT, @IDENT_LIST, @LENGTH_UNIT, @URI, @WRAP, @NUMBER, @COLOR);
    my $do_token_check = 1;
    my $only_ident     = 1;
    my $is_generic     = 0;
    my $curlist        = \@base;

    for my $tok (split(/ +/, $descriptor)) {
        next if $tok eq '';
        my ($key, $val);
        if ($tok =~ /^([^:]*):(.*)\z/) { $key = $1; $val = $2; }
        else                           { $key = $tok; $val = undef; }
        my $v0 = (defined($val) && length($val)) ? substr($val, 0, 1) : '';

        if ($key eq 'WRAP') {
            push @WRAP, { key => $key, val => $val };
            $only_ident = 0;
        } elsif ($key eq 'NUMBER') {
            if    ($v0 eq '(') { $curlist = \@NUMBER; }
            elsif ($v0 eq ')') { $curlist = \@base; }
            else               { push @NUMBER, { key => $key, val => $val }; }
            $only_ident = 0;
        } elsif ($key eq 'IDENT') {
            if    ($v0 eq '(')                       { $curlist = \@IDENT; }
            elsif ($v0 eq ')')                       { $curlist = \@base; }
            elsif (defined($val) && $val eq 'INHERIT') { push @IDENT, { key => 'INHERIT', val => undef }; }
            elsif (defined($val) && $val eq 'INITIAL') { push @IDENT, { key => 'INITIAL', val => undef }; }
            elsif (defined($val) && $val eq 'REVERT')  { push @IDENT, { key => 'REVERT',  val => undef }; }
            elsif (defined($val) && $val eq 'UNSET')   { push @IDENT, { key => 'UNSET',   val => undef }; }
            # else: no-op (matches C: closing handled above, nothing else added)
        } elsif ($key eq 'IDENT_LIST') {
            if    ($v0 eq '(') { $curlist = \@IDENT_LIST; }
            elsif ($v0 eq ')') { $curlist = \@base; }
        } elsif ($key eq 'LENGTH_UNIT') {
            if    ($v0 eq '(') { $curlist = \@LENGTH_UNIT; }
            elsif ($v0 eq ')') { $curlist = \@base; }
            $only_ident     = 0;
            $do_token_check = 0;
        } elsif ($key eq 'COLOR') {
            push @COLOR, { key => $key, val => $val };
            $do_token_check = 0;
            $only_ident     = 0;
        } elsif ($key eq 'URI') {
            push @URI, { key => $key, val => $val };
            $only_ident = 0;
        } elsif ($key eq 'GENERIC') {
            $is_generic = 1;
        } else {
            push @$curlist, { key => $key, val => $val };
        }
    }

    die "incorrect base element count (got ${\ scalar(@base)} expected 1) for: $descriptor\n"
        unless scalar(@base) == 1;
    my $pid = $base[0];

    my $o = output_header($descriptor, $pid, $is_generic);

    if (scalar(@WRAP) > 0) {
        $o .= output_wrap($pid, \@WRAP);
    } else {
        $o .= output_token_type_check($do_token_check, \@IDENT, \@URI, \@NUMBER);

        $o .= output_ident($only_ident, $pid, \@IDENT) if scalar(@IDENT) > 0;
        $o .= output_uri($pid, \@URI)                  if scalar(@URI) > 0;
        $o .= output_number($pid, \@NUMBER)            if scalar(@NUMBER) > 0;

        if    (scalar(@COLOR) > 0)       { $o .= output_color($pid, \@COLOR); }
        elsif (scalar(@LENGTH_UNIT) > 0) { $o .= output_length_unit($pid, \@LENGTH_UNIT); }
        elsif (scalar(@IDENT_LIST) > 0)  { $o .= output_ident_list($pid, \@IDENT_LIST); }
        else                             { $o .= output_invalidcss(); }

        $o .= output_footer();
    }
    return $o;
}

# ---------------------------------------------------------------------------
# output_* routines - direct ports of the C fprintf blocks.
# ---------------------------------------------------------------------------
sub output_header {
    my ($descriptor, $pid, $is_generic) = @_;
    my $key       = $pid->{key};
    my $op_doc    = $is_generic ? " * \\param op\t Bytecode OpCode for CSS property to encode\n" : "";
    my $op_param  = $is_generic ? ", enum css_properties_e op" : "";
    return
        "/*\n"
      . " * This file was generated by LibCSS gen_parser \n"
      . " * \n"
      . " * Generated from:\n"
      . " *\n"
      . " * $descriptor\n"
      . " * \n"
      . " * Licensed under the MIT License,\n"
      . " *\t\t  http://www.opensource.org/licenses/mit-license.php\n"
      . " * Copyright 2010 The NetSurf Browser Project.\n"
      . " */\n"
      . "\n"
      . "#include <assert.h>\n"
      . "#include <string.h>\n"
      . "\n"
      . "#include \"bytecode/bytecode.h\"\n"
      . "#include \"bytecode/opcodes.h\"\n"
      . "#include \"parse/properties/properties.h\"\n"
      . "#include \"parse/properties/utils.h\"\n"
      . "\n"
      . "/**\n"
      . " * Parse $key\n"
      . " *\n"
      . " * \\param c\t  Parsing context\n"
      . " * \\param vector  Vector of tokens to process\n"
      . " * \\param ctx\t  Pointer to vector iteration context\n"
      . " * \\param result  resulting style\n"
      . $op_doc
      . " * \\return CSS_OK on success,\n"
      . " *\t   CSS_NOMEM on memory exhaustion,\n"
      . " *\t   CSS_INVALID if the input is not valid\n"
      . " *\n"
      . " * Post condition: \\a *ctx is updated with the next token to process\n"
      . " *\t\t   If the input is invalid, then \\a *ctx remains unchanged.\n"
      . " */\n"
      . "css_error css__parse_$key(css_language *c,\n"
      . "\t\tconst parserutils_vector *vector, int32_t *ctx,\n"
      . "\t\tcss_style *result$op_param)\n"
      . "{\n";
}

sub output_token_type_check {
    my ($do_token_check, $IDENT, $URI, $NUMBER) = @_;
    my $o =
        "\tint32_t orig_ctx = *ctx;\n"
      . "\tcss_error error;\n"
      . "\tconst css_token *token;\n"
      . "\tbool match;\n\n"
      . "\ttoken = parserutils_vector_iterate(vector, ctx);\n"
      . "\tif (" . ($do_token_check ? "(" : "") . "token == NULL" . ($do_token_check ? ")" : "");

    if ($do_token_check) {
        my $prev = 0;
        $o .= " || (";
        if (scalar(@$IDENT) > 0) {
            $o .= "(token->type != CSS_TOKEN_IDENT)";
            $prev = 1;
        }
        if (scalar(@$URI) > 0) {
            $o .= " && " if $prev;
            $o .= "(token->type != CSS_TOKEN_URI)";
            $prev = 1;
        }
        if (scalar(@$NUMBER) > 0) {
            $o .= " && " if $prev;
            $o .= "(token->type != CSS_TOKEN_NUMBER)";
            $prev = 1;
        }
        $o .= ")";
    }

    $o .= ") {\n\t\t*ctx = orig_ctx;\n\t\treturn CSS_INVALID;\n\t}\n\n\t";
    return $o;
}

sub output_ident {
    my ($only_ident, $pid, $IDENT) = @_;
    my $o = '';
    for my $ckv (@$IDENT) {
        $o .= "if (";
        if (!$only_ident) {
            $o .= "(token->type == CSS_TOKEN_IDENT) &&\n\t\t\t";
        }
        $o .= "(lwc_string_caseless_isequal(\n"
            . "\t\t\ttoken->idata, c->strings[$ckv->{key}],\n"
            . "\t\t\t&match) == lwc_error_ok && match)) {\n";
        if ($ckv->{key} eq 'INHERIT') {
            $o .= "\t\terror = css_stylesheet_style_inherit(result,\n\t\t\t\t$pid->{val});\n\n";
        } elsif ($ckv->{key} eq 'INITIAL') {
            $o .= "\t\terror = css_stylesheet_style_initial(result,\n\t\t\t\t$pid->{val});\n\n";
        } elsif ($ckv->{key} eq 'REVERT') {
            $o .= "\t\terror = css_stylesheet_style_revert(result,\n\t\t\t\t$pid->{val});\n\n";
        } elsif ($ckv->{key} eq 'UNSET') {
            $o .= "\t\terror = css_stylesheet_style_unset(result,\n\t\t\t\t$pid->{val});\n\n";
        } else {
            $o .= "\t\terror = css__stylesheet_style_appendOPV(result,\n"
                . "\t\t\t\t$pid->{val},\n"
                . "\t\t\t\t$ckv->{val});\n\n";
        }
        $o .= "\t} else ";
    }
    return $o;
}

sub output_uri {
    my ($pid, $kvlist) = @_;
    my $ckv = $kvlist->[0];
    return
        "if (token->type == CSS_TOKEN_URI) {\n"
      . "\t\tlwc_string *uri = NULL;\n"
      . "\t\tuint32_t uri_snumber;\n"
      . "\n"
      . "\t\terror = c->sheet->resolve(c->sheet->resolve_pw,\n"
      . "\t\t\t\tc->sheet->url,\n"
      . "\t\t\t\ttoken->idata, &uri);\n"
      . "\t\tif (error != CSS_OK) {\n"
      . "\t\t\t*ctx = orig_ctx;\n"
      . "\t\t\treturn error;\n"
      . "\t\t}\n"
      . "\n"
      . "\t\terror = css__stylesheet_string_add(c->sheet, uri, &uri_snumber);\n"
      . "\t\tif (error != CSS_OK) {\n"
      . "\t\t\t*ctx = orig_ctx;\n"
      . "\t\t\treturn error;\n"
      . "\t\t}\n"
      . "\n"
      . "\t\terror = css__stylesheet_style_appendOPV(result, $pid->{val}, 0, $ckv->{val});\n"
      . "\t\tif (error != CSS_OK) {\n"
      . "\t\t\t*ctx = orig_ctx;\n"
      . "\t\t\treturn error;\n"
      . "\t\t}\n"
      . "\n"
      . "\t\terror = css__stylesheet_style_append(result, uri_snumber);\n"
      . "\t} else ";
}

sub output_number {
    my ($pid, $kvlist) = @_;
    my $ckv = $kvlist->[0];
    my $o =
        "if (token->type == CSS_TOKEN_NUMBER) {\n"
      . "\t\tcss_fixed num = 0;\n"
      . "\t\tsize_t consumed = 0;\n\n"
      . "\t\tnum = css__number_from_lwc_string(token->idata, $ckv->{key}, &consumed);\n"
      . "\t\t/* Invalid if there are trailing characters */\n"
      . "\t\tif (consumed != lwc_string_length(token->idata)) {\n"
      . "\t\t\t*ctx = orig_ctx;\n"
      . "\t\t\treturn CSS_INVALID;\n"
      . "\t\t}\n";

    for (my $i = 1; $i < scalar(@$kvlist); $i++) {
        my $ulkv = $kvlist->[$i];
        if ($ulkv->{key} eq 'RANGE') {
            $o .= "\t\tif ($ulkv->{val}) {\n"
                . "\t\t\t*ctx = orig_ctx;\n"
                . "\t\t\treturn CSS_INVALID;\n"
                . "\t\t}\n\n";
        }
    }

    $o .= "\t\terror = css__stylesheet_style_appendOPV(result, $pid->{val}, 0, $ckv->{val});\n"
        . "\t\tif (error != CSS_OK) {\n"
        . "\t\t\t*ctx = orig_ctx;\n"
        . "\t\t\treturn error;\n"
        . "\t\t}\n\n"
        . "\t\terror = css__stylesheet_style_append(result, num);\n"
        . "\t} else ";
    return $o;
}

sub output_color {
    my ($pid, $kvlist) = @_;
    return
        "{\n"
      . "\t\tuint16_t value = 0;\n"
      . "\t\tuint32_t color = 0;\n"
      . "\t\t*ctx = orig_ctx;\n\n"
      . "\t\terror = css__parse_colour_specifier(c, vector, ctx, &value, &color);\n"
      . "\t\tif (error != CSS_OK) {\n"
      . "\t\t\t*ctx = orig_ctx;\n"
      . "\t\t\treturn error;\n"
      . "\t\t}\n\n"
      . "\t\terror = css__stylesheet_style_appendOPV(result, $pid->{val}, 0, value);\n"
      . "\t\tif (error != CSS_OK) {\n"
      . "\t\t\t*ctx = orig_ctx;\n"
      . "\t\t\treturn error;\n"
      . "\t\t}\n"
      . "\n"
      . "\t\tif (value == COLOR_SET)\n"
      . "\t\t\terror = css__stylesheet_style_append(result, color);\n"
      . "\t}\n\n";
}

sub output_length_unit {
    my ($pid, $kvlist) = @_;
    my $ckv = $kvlist->[0];
    my $o =
        "{\n"
      . "\t\tcss_fixed length = 0;\n"
      . "\t\tuint32_t unit = 0;\n"
      . "\t\t*ctx = orig_ctx;\n\n"
      . "\t\terror = css__parse_unit_specifier(c, vector, ctx, $ckv->{key}, &length, &unit);\n"
      . "\t\tif (error != CSS_OK) {\n"
      . "\t\t\t*ctx = orig_ctx;\n"
      . "\t\t\treturn error;\n"
      . "\t\t}\n\n";

    for (my $i = 1; $i < scalar(@$kvlist); $i++) {
        my $ulkv = $kvlist->[$i];
        if ($ulkv->{key} eq 'ALLOW') {
            $o .= "\t\tif (($ulkv->{val}) == false) {\n"
                . "\t\t\t*ctx = orig_ctx;\n"
                . "\t\t\treturn CSS_INVALID;\n"
                . "\t\t}\n\n";
        } elsif ($ulkv->{key} eq 'DISALLOW') {
            $o .= "\t\tif ($ulkv->{val}) {\n"
                . "\t\t\t*ctx = orig_ctx;\n"
                . "\t\t\treturn CSS_INVALID;\n"
                . "\t\t}\n\n";
        } elsif ($ulkv->{key} eq 'MASK') {
            $o .= "\t\tif ((unit & $ulkv->{val} ) == 0) {\n"
                . "\t\t\t*ctx = orig_ctx;\n"
                . "\t\t\treturn CSS_INVALID;\n"
                . "\t\t}\n\n";
        } elsif ($ulkv->{key} eq 'RANGE') {
            $o .= "\t\tif (length $ulkv->{val}) {\n"
                . "\t\t\t*ctx = orig_ctx;\n"
                . "\t\t\treturn CSS_INVALID;\n"
                . "\t\t}\n\n";
        }
    }

    $o .= "\t\terror = css__stylesheet_style_appendOPV(result, $pid->{val}, 0, $ckv->{val});\n"
        . "\t\tif (error != CSS_OK) {\n"
        . "\t\t\t*ctx = orig_ctx;\n"
        . "\t\t\treturn error;\n"
        . "\t\t}\n"
        . "\n"
        . "\t\terror = css__stylesheet_style_vappend(result, 2, length, unit);\n"
        . "\t}\n\n";
    return $o;
}

sub output_ident_list {
    my ($pid, $kvlist) = @_;
    my $ckv = $kvlist->[0];   # list type : opv value

    if ($ckv->{key} ne 'STRING_OPTNUM') {
        die "unknown IDENT list type $ckv->{key}\n";
    }
    if (scalar(@$kvlist) < 2) {
        die "Not enough parameters to IDENT list type $ckv->{key}\n";
    }

    my $ikv = $kvlist->[1];   # numeric default : end condition

    return
        "{\n"
      . "\t\terror = css__stylesheet_style_appendOPV(result, $pid->{val}, 0, $ckv->{val});\n"
      . "\t\tif (error != CSS_OK) {\n"
      . "\t\t\t*ctx = orig_ctx;\n"
      . "\t\t\treturn error;\n"
      . "\t\t}\n\n"
      . "\t\twhile ((token != NULL) && (token->type == CSS_TOKEN_IDENT)) {\n"
      . "\t\t\tuint32_t snumber;\n"
      . "\t\t\tcss_fixed num;\n"
      . "\t\t\tint pctx;\n\n"
      . "\t\t\terror = css__stylesheet_string_add(c->sheet, lwc_string_ref(token->idata), &snumber);\n"
      . "\t\t\tif (error != CSS_OK) {\n"
      . "\t\t\t\t*ctx = orig_ctx;\n"
      . "\t\t\t\treturn error;\n"
      . "\t\t\t}\n\n"
      . "\t\t\terror = css__stylesheet_style_append(result, snumber);\n"
      . "\t\t\tif (error != CSS_OK) {\n"
      . "\t\t\t\t*ctx = orig_ctx;\n"
      . "\t\t\t\treturn error;\n"
      . "\t\t\t}\n\n"
      . "\t\t\tconsumeWhitespace(vector, ctx);\n\n"
      . "\t\t\tpctx = *ctx;\n"
      . "\t\t\ttoken = parserutils_vector_iterate(vector, ctx);\n"
      . "\t\t\tif ((token != NULL) && (token->type == CSS_TOKEN_NUMBER)) {\n"
      . "\t\t\t\tsize_t consumed = 0;\n\n"
      . "\t\t\t\tnum = css__number_from_lwc_string(token->idata, true, &consumed);\n"
      . "\t\t\t\tif (consumed != lwc_string_length(token->idata)) {\n"
      . "\t\t\t\t\t*ctx = orig_ctx;\n"
      . "\t\t\t\t\treturn CSS_INVALID;\n"
      . "\t\t\t\t}\n"
      . "\t\t\t\tconsumeWhitespace(vector, ctx);\n\n"
      . "\t\t\t\tpctx = *ctx;\n"
      . "\t\t\t\ttoken = parserutils_vector_iterate(vector, ctx);\n"
      . "\t\t\t} else {\n"
      . "\t\t\t\tnum = INTTOFIX($ikv->{key});\n"
      . "\t\t\t}\n\n"
      . "\t\t\terror = css__stylesheet_style_append(result, num);\n"
      . "\t\t\tif (error != CSS_OK) {\n"
      . "\t\t\t\t*ctx = orig_ctx;\n"
      . "\t\t\t\treturn error;\n"
      . "\t\t\t}\n\n"
      . "\t\t\tif (token == NULL)\n"
      . "\t\t\t\tbreak;\n\n"
      . "\t\t\tif (token->type == CSS_TOKEN_IDENT) {\n"
      . "\t\t\t\terror = css__stylesheet_style_append(result, $ckv->{val});\n"
      . "\t\t\t\tif (error != CSS_OK) {\n"
      . "\t\t\t\t\t*ctx = orig_ctx;\n"
      . "\t\t\t\t\treturn error;\n"
      . "\t\t\t\t}\n"
      . "\t\t\t} else {\n"
      . "\t\t\t\t*ctx = pctx; /* rewind one token back */\n"
      . "\t\t\t}\n"
      . "\t\t}\n\n"
      . "\t\terror = css__stylesheet_style_append(result, $ikv->{val});\n"
      . "\t}\n\n";
}

sub output_invalidcss {
    return "{\n\t\terror = CSS_INVALID;\n\t}\n\n";
}

sub output_footer {
    return
        "\tif (error != CSS_OK)\n"
      . "\t\t*ctx = orig_ctx;\n"
      . "\t\n"
      . "\treturn error;\n"
      . "}\n\n";
}

sub output_wrap {
    my ($pid, $WRAP) = @_;
    my $ckv = $WRAP->[0];
    return "\treturn $ckv->{val}(c, vector, ctx, result, $pid->{val});\n}\n";
}
