/* Generated by scripts/port_list_style_vs2008.py from
 * libcss/src/select/format_list_style.c. Do not edit. */
/*
 * This file is part of LibCSS
 * Licensed under the MIT License,
 *		  http://www.opensource.org/licenses/mit-license.php
 * Copyright 2021 Vincent Sanders <vince@netsurf-browser.org>
 */

#include "select/propget.h"
#include "utils/utils.h"

#define SYMBOL_SIZE 8
typedef char symbol_t[SYMBOL_SIZE];

/**
 * numeric representation of the value using a system
 */
struct numeric {
	uint8_t *val; /* buffer containing the numeric values */
	size_t len; /* length of alen */
	size_t used; /* number of numeric values used */
	bool negative; /* if the value is negative */
};

/**
 * list counter style
 */
struct list_counter_style {
	/** style name for debug purposes */
	const char *name;
	/** function to calculate the system */
	css_error (*system)(int value, const struct list_counter_style *cstyle, struct numeric *nval);
	/** fallback style if this system fails */
	const struct list_counter_style* fallback;
	/** array of symbols which represent this style */
	const symbol_t *symbols;
	/** symbol weights for additive schemes */
	const int *weights;
	/** number of items in symbol and weight table */
	const size_t items;
	/** range of acceptable values */
	struct {
		const int start; /**< first acceptable value for this style */
		const int end; /**< last acceptable value for this style */
	} range;

	/** padding formatting */
	struct {
		const unsigned int length;
		const symbol_t value;
	} pad;
	/** negative value formating */
	struct {
		const char *pre;
		const char *post;
	} negative;
	/** prefix formatting */
	const char *prefix;
	/** suffix formatting */
	const char *suffix;
};


/**
 * Copy a null-terminated UTF-8 string to buffer at offset, if there is space
 *
 * \param[in] buf    The output buffer
 * \param[in] buflen The length of \a buf
 * \param[in] pos    Current position in \a buf
 * \param[in] str    The string to copy into \a buf
 * \return The number of bytes needed in the output buffer which may be
 *         larger than \a buflen but the buffer will not be overrun
 */
static inline size_t
copy_string(char *buf, const size_t buflen, size_t pos, const char *str)
{
	size_t sidx = 0; /* current string index */

	while (str[sidx] != '\0') {
		if (pos < buflen) {
			buf[pos] = str[sidx];
		}
		pos++;
		sidx++;
	}

	return sidx;
}

/**
 * Copy a UTF-8 symbol to buffer at offset, if there is space
 *
 * \param[in] buf    The output buffer
 * \param[in] buflen The length of \a buf
 * \param[in] pos    Current position in \a buf
 * \param[in] symbol The symbol to copy into \a buf
 * \return The number of bytes needed in the output buffer which may be
 *         larger than \a buflen but the buffer will not be overrun
 */
static inline size_t
copy_symbol(char *buf, const size_t buflen, size_t pos, const symbol_t symbol)
{
	size_t sidx = 0; /* current symbol index */

	while ((sidx < sizeof(symbol_t)) && (symbol[sidx] != '\0')) {
		if (pos < buflen) {
			buf[pos] = symbol[sidx];
		}
		pos++;
		sidx++;
	}

	return sidx;
}

/**
 * maps numeric values to output values with a symbol table
 *
 * Takes a list of numeric values and for each one outputs the
 *   compete symbol (in utf8) to an output buffer.
 *
 * \param buf The output buffer
 * \param buflen the length of \a buf
 * \param aval array of alphabet values
 * \param alen The number of values in \a alen
 * \param symtab The symbol table
 * \param symtablen The number of symbols in \a symtab
 * \return The number of bytes needed in the output buffer whichmay be
 *         larger than \a buflen but the buffer will not be overrun
 */
static size_t
nval_to_symbols(struct numeric *nval,
		const struct list_counter_style *cstyle,
		char *buf, const size_t buflen)
{
	size_t oidx = 0;
	size_t aidx; /* numeral index */
	const char *suffix = "."; /* default sufffix string */
	const char *negative_pre = "-"; /* default negative string */

	/* prefix */
	if (cstyle->prefix != NULL) {
		oidx += copy_string(buf, buflen, oidx, cstyle->prefix);
	}

	/* negative pre */
	if (nval->negative) {
		if (cstyle->negative.pre != NULL) {
			negative_pre = cstyle->negative.pre;
		}
		oidx += copy_string(buf, buflen, oidx, negative_pre);
	}

	/* add padding if required */
	if (nval->used < cstyle->pad.length) {
		size_t pidx; /* padding index */
		for (pidx = cstyle->pad.length - nval->used; pidx > 0; pidx--) {
			oidx += copy_symbol(buf, buflen, oidx,
					cstyle->pad.value);
		}
	}

	/* map symbols */
	for (aidx = 0; aidx < nval->used; aidx++) {
		oidx += copy_symbol(buf, buflen, oidx,
				cstyle->symbols[nval->val[aidx]]);
	}

	/* negative post */
	if ((nval->negative) && (cstyle->negative.post != NULL)) {
		oidx += copy_string(buf, buflen, oidx, cstyle->negative.post);
	}

	/* suffix */
	if (cstyle->suffix != NULL) {
		suffix = cstyle->suffix;
	}
	oidx += copy_string(buf, buflen, oidx, suffix);

	return oidx;
}


/**
 * generate numeric symbol values
 *
 * fills array with numeric values that represent the input value
 *
 * \param ares Buffer to recive the converted values
 * \param alen the length of \a ares buffer
 * \param value The value to convert
 * \param cstyle The counter style in use
 * \return The length a complete conversion which may be larger than \a alen
 */
static css_error
calc_numeric_system(int value,
		    const struct list_counter_style *cstyle,
		    struct numeric *nval)
{
	size_t idx = 0;
	uint8_t *first;
	uint8_t *last;

	if (value == 0) {
		if (nval->len >= 1) {
			nval->val[0] = 0;
		}
		nval->used = 1;
		return CSS_OK;
	}

	if (value < 0) {
		nval->negative = true;
		value = abs(value);
	} else {
		nval->negative = false;
	}

	/* generate alphabet values in ascending order */
	while (value > 0) {
		if (idx < nval->len) {
			nval->val[idx] = value % cstyle->items;
		}
		idx++;
		value = value / cstyle->items;
	}

	/* put the values in decending order */
	first = nval->val;
	if (idx < nval->len) {
		last = first + (idx - 1);
	} else {
		last = first + (nval->len - 1);
	}
	while (first < last) {
		*first ^= *last;
		*last ^= *first;
		*first ^= *last;
		first++;
		last--;
	}

	nval->used = idx;

	return CSS_OK;
}


/**
 * generate cyclic symbol values
 *
 * fills array with cyclic values that represent the input value
 *
 * \param ares Buffer to recive the converted values
 * \param alen the length of \a ares buffer
 * \param value The value to convert
 * \param cstyle The counter style in use
 * \return The length a complete conversion which may be larger than \a alen
 */
static css_error
calc_cyclic_system(int value,
		    const struct list_counter_style *cstyle,
		    struct numeric *nval)
{
	if (nval->len == 0) {
		return CSS_INVALID;
	}
	if (cstyle->items == 1) {
		/* there is only one symbol so select it */
		nval->val[0] = 0;
	} else {
		nval->val[0] = (value - 1) % cstyle->items;
	}
	nval->used = 1;
	nval->negative = false;

	return CSS_OK;
}


/**
 * generate addative symbol values
 *
 * fills array with numeric values that represent the input value
 *
 * \param ares Buffer to recive the converted values
 * \param alen the length of \a ares buffer
 * \param value The value to convert
 * \param wlen The number of weights
 * \return The length a complete conversion which may be larger than \a alen
 */
static css_error
calc_additive_system(int value,
		    const struct list_counter_style *cstyle,
		    struct numeric *nval)
{
	size_t widx; /* weight index */
	size_t aidx = 0; /* numerals used */
	size_t idx;
	size_t times; /* number of times a weight occours */

	/* ensure value is within acceptable range of this system */
	if ((value < cstyle->range.start) || (value > cstyle->range.end)) {
		return CSS_INVALID;
	}

	/* zero needs a specific weight */
	if (value == 0) {
		/* search weights for a zero entry */
		for (widx = 0; widx < cstyle->items; widx++) {
			if (cstyle->weights[widx] == 0) {
				if (nval->len > 0) {
					nval->val[0] = widx;
				}

				nval->used = 1;
				nval->negative = false;
				return CSS_OK;
			}
		}
		return CSS_INVALID;
	}

	/* negative values */
	if (value < 0) {
		nval->negative = true;
		value = abs(value);
	} else {
		nval->negative = false;
	}

	/* iterate over the available weights */
	for (widx = 0; widx < cstyle->items; widx++) {
		if (cstyle->weights[widx] == 0) {
			break;
		}
		times = value / cstyle->weights[widx];
		if (times > 0) {
			for (idx = 0;idx < times;idx++) {
				if (aidx < nval->len) {
					nval->val[aidx] = widx;
				}
				aidx++;
			}

			value -= times * cstyle->weights[widx];
		}
	}

	nval->used = aidx;

	return CSS_OK;
}


/**
 * generate alphabet symbol values for latin and greek labelling
 *
 * fills array with alphabet values suitable for the input value
 *
 * \param ares Buffer to recive the converted values
 * \param alen the length of \a ares buffer
 * \param value The value to convert
 * \param slen The number of symbols in the alphabet
 * \return The length a complete conversion which may be larger than \a alen
 */
static css_error
calc_alphabet_system(int value,
		     const struct list_counter_style *cstyle,
		     struct numeric *nval)
{
	size_t idx = 0;
	uint8_t *first;
	uint8_t *last;

	if (value < 1) {
		return CSS_INVALID;
	}

	/* generate alphabet values in ascending order */
	while (value > 0) {
		--value;
		if (idx < nval->len) {
			nval->val[idx] = value % cstyle->items;
		}
		idx++;
		value = value / cstyle->items;
	}

	/* put the values in decending order */
	first = nval->val;
	if (idx < nval->len) {
		last = first + (idx - 1);
	} else {
		last = first + (nval->len - 1);
	}
	while (first < last) {
		*first ^= *last;
		*last ^= *first;
		*first ^= *last;
		first++;
		last--;
	}

	nval->used = idx;
	nval->negative = false;

	return CSS_OK;
}


/**
 * Roman numeral conversion
 *
 * \return The number of numerals that are nesesary for full output
 */
static css_error
calc_roman_system(int value,
		  const struct list_counter_style *cstyle,
		  struct numeric *nval)
{
	const int S[]  = {    0,   2,   4,   2,   4,   2,   4 };
	size_t k = 0; /* index into output buffer */
	unsigned int i = 0; /* index into maps */
	int r;
	int r2 = 0;
	size_t L;

	assert(cstyle->items == 7);

	/* ensure value is within acceptable range of this system */
	if ((value < cstyle->range.start) || (value > cstyle->range.end)) {
		return CSS_INVALID;
	}

	L = cstyle->items - 1;

	while (value > 0) {
		if (cstyle->weights[i] <= value) {
			r = value / cstyle->weights[i];
			value = value - (r * cstyle->weights[i]);
			if (i < L) {
				/* lookahead */
				r2 = value / cstyle->weights[i+1];
			}
			if (i < L && r2 >= S[i+1]) {
				/* will violate repeat boundary on next pass */
				value = value - (r2 * cstyle->weights[i+1]);
				if (k < nval->len) {
					nval->val[k++] = i+1;
				}
				if (k < nval->len) {
					nval->val[k++] = i-1;
				}
			} else if (S[i] && r >= S[i]) {
				/* violated repeat boundary on this pass */
				if (k < nval->len) {
					nval->val[k++] = i;
				}
				if (k < nval->len) {
					nval->val[k++] = i-1;
				}
			} else {
				while ((r-- > 0) && (k < nval->len)) {
					nval->val[k++] = i;
				}
			}
		}
		i++;
	}

	nval->used = k;
	nval->negative = false;

	return CSS_OK;
}


/* tables for all the counter styles */

static const symbol_t decimal_symbols[] = {
	"0", "1", "2", "3", "4", "5", "6", "7", "8", "9"
};
static const struct list_counter_style lcs_decimal = {
	"decimal",
	calc_numeric_system,
	NULL,
	decimal_symbols,
	NULL,
	(sizeof(decimal_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};

static const symbol_t georgian_symbols[] = {
	                                        "\341\203\265",
	"\341\203\260", "\341\203\257", "\341\203\264", "\341\203\256", "\341\203\255", "\341\203\254", "\341\203\253", "\341\203\252", "\341\203\251",
	"\341\203\250", "\341\203\247", "\341\203\246", "\341\203\245", "\341\203\244", "\341\203\263", "\341\203\242", "\341\203\241", "\341\203\240",
	"\341\203\237", "\341\203\236", "\341\203\235", "\341\203\262", "\341\203\234", "\341\203\233", "\341\203\232", "\341\203\231", "\341\203\230",
	"\341\203\227", "\341\203\261", "\341\203\226", "\341\203\225", "\341\203\224", "\341\203\223", "\341\203\222", "\341\203\221", "\341\203\220",
};
static const int georgian_weights[] = {
	                                                10000,
	9000, 8000, 7000, 6000, 5000, 4000, 3000, 2000, 1000,
	900,  800,  700,  600,  500,  400,  300,  200,  100,
	90,   80,   70,   60,   50,   40,   30,   20,   10,
	9,    8,    7,    6,    5,    4,    3,    2,    1
};
static const struct list_counter_style lcs_georgian = {
	"georgian",
	calc_additive_system,
	&lcs_decimal,
	georgian_symbols,
	georgian_weights,
	(sizeof(georgian_symbols) / SYMBOL_SIZE),
	{ 1, 19999 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};


static const symbol_t upper_armenian_symbols[] = {
	"\325\224", "\325\223", "\325\222", "\325\221", "\325\220", "\325\217", "\325\216", "\325\215", "\325\214",
	"\325\213", "\325\212", "\325\211", "\325\210", "\325\207", "\325\206", "\325\205", "\325\204", "\325\203",
	"\325\202", "\325\201", "\325\200", "\324\277", "\324\276", "\324\275", "\324\274", "\324\273", "\324\272",
	"\324\271", "\324\270", "\324\267", "\324\266", "\324\265", "\324\264", "\324\263", "\324\262", "\324\261"
};
static const int armenian_weights[] = {
	9000, 8000, 7000, 6000, 5000, 4000, 3000, 2000, 1000,
	900,  800,  700,  600,  500,  400,  300,  200,  100,
	90,   80,   70,   60,   50,   40,   30,   20,   10,
	9,    8,    7,    6,    5,    4,    3,    2,    1
};
static const struct list_counter_style lcs_upper_armenian = {
	"upper-armenian",
	calc_additive_system,
	&lcs_decimal,
	upper_armenian_symbols,
	armenian_weights,
	(sizeof(upper_armenian_symbols) / SYMBOL_SIZE),
	{ 1, 9999 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};


static const symbol_t lower_armenian_symbols[] = {
	"\326\204", "\326\203", "\326\202", "\326\201", "\326\200", "\325\277", "\325\276", "\325\275", "\325\274",
	"\325\273", "\325\272", "\325\271", "\325\270", "\325\267", "\325\266", "\325\265", "\325\264", "\325\263",
	"\325\262", "\325\261", "\325\260", "\325\257", "\325\256", "\325\255", "\325\254", "\325\253", "\325\252",
	"\325\251", "\325\250", "\325\247", "\325\246", "\325\245", "\325\244", "\325\243", "\325\242", "\325\241"
};
static const struct list_counter_style lcs_lower_armenian = {
	"lower-armenian",
	calc_additive_system,
	&lcs_decimal,
	lower_armenian_symbols,
	armenian_weights,
	(sizeof(lower_armenian_symbols) / SYMBOL_SIZE),
	{ 1, 9999 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};


static const struct list_counter_style lcs_decimal_leading_zero = {
	"decimal-leading-zero",
	calc_numeric_system,
	NULL,
	decimal_symbols,
	NULL,
	(sizeof(decimal_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 2, "0" },
	{ NULL, NULL },
	NULL,
	NULL
};


static const symbol_t lower_greek_symbols[] = {
	"\316\261", "\316\262", "\316\263", "\316\264", "\316\265", "\316\266", "\316\267", "\316\270", "\316\271", "\316\272",
	"\316\273", "\316\274", "\316\275", "\316\276", "\316\277", "\317\200", "\317\201", "\317\203", "\317\204", "\317\205",
	"\317\206", "\317\207", "\317\210", "\317\211"
};
static const struct list_counter_style lcs_lower_greek = {
	"lower-greek",
	calc_alphabet_system,
	&lcs_decimal,
	lower_greek_symbols,
	NULL,
	(sizeof(lower_greek_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};


static const symbol_t upper_alpha_symbols[] = {
	"A", "B", "C", "D", "E", "F", "G", "H", "I", "J",
	"K", "L", "M", "N", "O", "P", "Q", "R", "S", "T",
	"U", "V", "W", "X", "Y", "Z"
};
static const struct list_counter_style lcs_upper_alpha = {
	"upper-alpha",
	calc_alphabet_system,
	&lcs_decimal,
	upper_alpha_symbols,
	NULL,
	(sizeof(upper_alpha_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};


static const symbol_t lower_alpha_symbols[] = {
	"a", "b", "c", "d", "e", "f", "g", "h", "i", "j",
	"k", "l", "m", "n", "o", "p", "q", "r", "s", "t",
	"u", "v", "w", "x", "y", "z"
};
static struct list_counter_style lcs_lower_alpha = {
	"lower-alpha",
	calc_alphabet_system,
	&lcs_decimal,
	lower_alpha_symbols,
	NULL,
	(sizeof(lower_alpha_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};


static const int roman_weights[] = {
	1000, 500, 100,  50,  10,   5,   1
};
static const symbol_t upper_roman_symbols[] = {
	"M", "D", "C", "L", "X", "V", "I"
};
static const struct list_counter_style lcs_upper_roman = {
	"upper-roman",
	calc_roman_system,
	&lcs_decimal,
	upper_roman_symbols,
	roman_weights,
	(sizeof(upper_roman_symbols) / SYMBOL_SIZE),
	{ 1, 3999 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};


static const symbol_t lower_roman_symbols[] = {
	"m", "d", "c", "l", "x", "v", "i"
};
static const struct list_counter_style lcs_lower_roman = {
	"lower-roman",
	calc_roman_system,
	&lcs_decimal,
	lower_roman_symbols,
	roman_weights,
	(sizeof(lower_roman_symbols) / SYMBOL_SIZE),
	{ 1, 3999 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};

static const symbol_t disc_symbols[] = { "\xE2\x80\xA2"}; /* 2022 BULLET */
static const struct list_counter_style lcs_disc = {
	"disc",
	calc_cyclic_system,
	NULL,
	disc_symbols,
	NULL,
	(sizeof(disc_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	" "
};

static const symbol_t circle_symbols[] = { "\342\227\213"}; /* 25CB WHITE CIRCLE */
static const struct list_counter_style lcs_circle = {
	"circle",
	calc_cyclic_system,
	NULL,
	circle_symbols,
	NULL,
	(sizeof(circle_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	" "
};

static const symbol_t square_symbols[] = { "\342\226\252"}; /* 25AA BLACK SMALL SQUARE */
static const struct list_counter_style lcs_square = {
	"square",
	calc_cyclic_system,
	NULL,
	square_symbols,
	NULL,
	(sizeof(square_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	" "
};

static const symbol_t binary_symbols[] = { "0", "1" };
static const struct list_counter_style lcs_binary = {
	"binary",
	calc_numeric_system,
	NULL,
	binary_symbols,
	NULL,
	(sizeof(binary_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};

static const symbol_t octal_symbols[] = {
	"0", "1", "2", "3", "4", "5", "6", "7"
};
static const struct list_counter_style lcs_octal = {
	"octal",
	calc_numeric_system,
	NULL,
	octal_symbols,
	NULL,
	(sizeof(octal_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};


static const symbol_t lower_hexadecimal_symbols[] = {
	"0", "1", "2", "3", "4", "5", "6", "7", "8", "9",
	"a", "b", "c", "d", "e", "f"
};
static const struct list_counter_style lcs_lower_hexadecimal = {
	"lower-hexadecimal",
	calc_numeric_system,
	NULL,
	lower_hexadecimal_symbols,
	NULL,
	(sizeof(lower_hexadecimal_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};

static const symbol_t upper_hexadecimal_symbols[] = {
	"0", "1", "2", "3", "4", "5", "6", "7", "8", "9",
	"a", "b", "c", "d", "e", "f"
};
static const struct list_counter_style lcs_upper_hexadecimal = {
	"upper-hexadecimal",
	calc_numeric_system,
	NULL,
	upper_hexadecimal_symbols,
	NULL,
	(sizeof(upper_hexadecimal_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};

static const symbol_t arabic_indic_symbols[] = {
	"\xd9\xa0", "\xd9\xa1", "\xd9\xa2", "\xd9\xa3", "\xd9\xa4", "\xd9\xa5", "\xd9\xa6", "\xd9\xa7", "\xd9\xa8", "\xd9\xa9"
};
static const struct list_counter_style lcs_arabic_indic = {
	"arabic-indic",
	calc_numeric_system,
	NULL,
	arabic_indic_symbols,
	NULL,
	(sizeof(arabic_indic_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};

static const symbol_t bengali_symbols[] = {
	"\340\247\246", "\340\247\247", "\340\247\250", "\340\247\251", "\340\247\252", "\340\247\253", "\340\247\254", "\340\247\255", "\340\247\256", "\340\247\257"
};
static const struct list_counter_style lcs_bengali = {
	"bengali",
	calc_numeric_system,
	NULL,
	bengali_symbols,
	NULL,
	(sizeof(bengali_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};

static const symbol_t cambodian_symbols[] = {
	"\341\237\240", "\341\237\241", "\341\237\242", "\341\237\243", "\341\237\244", "\341\237\245", "\341\237\246", "\341\237\247", "\341\237\250", "\341\237\251"
};
static const struct list_counter_style lcs_cambodian = {
	"cambodian",
	calc_numeric_system,
	NULL,
	cambodian_symbols,
	NULL,
	(sizeof(cambodian_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};

static const symbol_t cjk_decimal_symbols[] = {
	"\343\200\207", "\344\270\200", "\344\272\214", "\344\270\211", "\345\233\233", "\344\272\224", "\345\205\255", "\344\270\203", "\345\205\253", "\344\271\235"
};
static const struct list_counter_style lcs_cjk_decimal = {
	"cjk-decimal",
	calc_numeric_system,
	NULL,
	cjk_decimal_symbols,
	NULL,
	(sizeof(cjk_decimal_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	"\343\200\201"
};

static const symbol_t devanagari_symbols[] = {
	"\340\245\246", "\340\245\247", "\340\245\250", "\340\245\251", "\340\245\252", "\340\245\253", "\340\245\254", "\340\245\255", "\340\245\256", "\340\245\257"
};
static const struct list_counter_style lcs_devanagari = {
	"devanagari",
	calc_numeric_system,
	NULL,
	devanagari_symbols,
	NULL,
	(sizeof(devanagari_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};

static const symbol_t gujarati_symbols[] = {
	"\340\253\246", "\340\253\247", "\340\253\250", "\340\253\251", "\340\253\252", "\340\253\253", "\340\253\254", "\340\253\255", "\340\253\256", "\340\253\257"
};
static const struct list_counter_style lcs_gujarati = {
	"gujarati",
	calc_numeric_system,
	NULL,
	gujarati_symbols,
	NULL,
	(sizeof(gujarati_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};

static const symbol_t gurmukhi_symbols[] = {
	"\340\251\246", "\340\251\247", "\340\251\250", "\340\251\251", "\340\251\252", "\340\251\253", "\340\251\254", "\340\251\255", "\340\251\256", "\340\251\257"
};
static const struct list_counter_style lcs_gurmukhi = {
	"gurmukhi",
	calc_numeric_system,
	NULL,
	gurmukhi_symbols,
	NULL,
	(sizeof(gurmukhi_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};

static const int hebrew_weights[] = {
				                                          10000,
	9000, 8000, 7000, 6000, 5000, 4000, 3000, 2000,                   1000,
	                              400,  300,  200,                    100,
	90,   80,   70,   60,   50,   40,   30,   20, 19, 18, 17, 16, 15, 10,
	9,    8,    7,    6,    5,    4,    3,    2,                      1
};
static const symbol_t hebrew_symbols[] = {
	"\xD7\x99\xD7\xB3",
	"\xD7\x98\xD7\xB3", "\xD7\x97\xD7\xB3", "\xD7\x96\xD7\xB3", "\xD7\x95\xD7\xB3", "\xD7\x94\xD7\xB3", "\xD7\x93\xD7\xB3", "\xD7\x92\xD7\xB3", "\xD7\x91\xD7\xB3", "\xD7\x90\xD7\xB3",
	"\xD7\xAA", "\xD7\xA9", "\xD7\xA8", "\xD7\xA7",
	"\xD7\xA6", "\xD7\xA4", "\xD7\xA2", "\xD7\xA1", "\xD7\xA0", "\xD7\x9E", "\xD7\x9C", /* 20 */"\xD7\x9B", "\xD7\x99\xD7\x98", "\xD7\x99\xD7\x97", "\xD7\x99\xD7\x96", "\xD7\x98\xD7\x96", "\xD7\x98\xD7\x95", "\xD7\x99",
	"\xD7\x98", "\xD7\x97", "\xD7\x96", "\xD7\x95", "\xD7\x94", "\xD7\x93", "\xD7\x92", "\xD7\x91", "\xD7\x90"
};
static const struct list_counter_style lcs_hebrew = {
	"hebrew",
	calc_additive_system,
	&lcs_decimal,
	hebrew_symbols,
	hebrew_weights,
	(sizeof(hebrew_symbols) / SYMBOL_SIZE),
	{ 1, 10999 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};

static const symbol_t kannada_symbols[] = {
	"\xE0\xB3\xA6", "\xE0\xB3\xA7", "\xE0\xB3\xA8", "\xE0\xB3\xA9", "\xE0\xB3\xAA", "\xE0\xB3\xAB", "\xE0\xB3\xAC", "\xE0\xB3\xAD", "\xE0\xB3\xAE", "\xE0\xB3\xAF"
};
static const struct list_counter_style lcs_kannada = {
	"kannada",
	calc_numeric_system,
	NULL,
	kannada_symbols,
	NULL,
	(sizeof(kannada_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};

static const symbol_t lao_symbols[] = {
	"\340\273\220", "\340\273\221", "\340\273\222", "\340\273\223", "\340\273\224", "\340\273\225", "\340\273\226", "\340\273\227", "\340\273\230", "\340\273\231"
};
static const struct list_counter_style lcs_lao = {
	"lao",
	calc_numeric_system,
	NULL,
	lao_symbols,
	NULL,
	(sizeof(lao_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};

static const symbol_t malayalam_symbols[] = {
	"\340\265\246", "\340\265\247", "\340\265\250", "\340\265\251", "\340\265\252", "\340\265\253", "\340\265\254", "\340\265\255", "\340\265\256", "\340\265\257"
};
static const struct list_counter_style lcs_malayalam = {
	"malayalam",
	calc_numeric_system,
	NULL,
	malayalam_symbols,
	NULL,
	(sizeof(malayalam_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};

static const symbol_t mongolian_symbols[] = {
	"\341\240\220", "\341\240\221", "\341\240\222", "\341\240\223", "\341\240\224", "\341\240\225", "\341\240\226", "\341\240\227", "\341\240\230", "\341\240\231"
};
static const struct list_counter_style lcs_mongolian = {
	"mongolian",
	calc_numeric_system,
	NULL,
	mongolian_symbols,
	NULL,
	(sizeof(mongolian_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};

static const symbol_t myanmar_symbols[] = {
	"\341\201\200", "\341\201\201", "\341\201\202", "\341\201\203", "\341\201\204", "\341\201\205", "\341\201\206", "\341\201\207", "\341\201\210", "\341\201\211"
};
static const struct list_counter_style lcs_myanmar = {
	"myanmar",
	calc_numeric_system,
	NULL,
	myanmar_symbols,
	NULL,
	(sizeof(myanmar_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};

static const symbol_t oriya_symbols[] = {
	"\340\255\246", "\340\255\247", "\340\255\250", "\340\255\251", "\340\255\252", "\340\255\253", "\340\255\254", "\340\255\255", "\340\255\256", "\340\255\257"
};
static const struct list_counter_style lcs_oriya = {
	"oriya",
	calc_numeric_system,
	NULL,
	oriya_symbols,
	NULL,
	(sizeof(oriya_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};

static const symbol_t persian_symbols[] = {
	"\333\260", "\333\261", "\333\262", "\333\263", "\333\264", "\333\265", "\333\266", "\333\267", "\333\270", "\333\271"
};
static const struct list_counter_style lcs_persian = {
	"persian",
	calc_numeric_system,
	NULL,
	persian_symbols,
	NULL,
	(sizeof(persian_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};

static const symbol_t tamil_symbols[] = {
	"\340\257\246", "\340\257\247", "\340\257\250", "\340\257\251", "\340\257\252", "\340\257\253", "\340\257\254", "\340\257\255", "\340\257\256", "\340\257\257"
};
static const struct list_counter_style lcs_tamil = {
	"tamil",
	calc_numeric_system,
	NULL,
	tamil_symbols,
	NULL,
	(sizeof(tamil_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};

static const symbol_t telugu_symbols[] = {
	"\340\261\246", "\340\261\247", "\340\261\250", "\340\261\251", "\340\261\252", "\340\261\253", "\340\261\254", "\340\261\255", "\340\261\256", "\340\261\257"
};
static const struct list_counter_style lcs_telugu = {
	"telugu",
	calc_numeric_system,
	NULL,
	telugu_symbols,
	NULL,
	(sizeof(telugu_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};

static const symbol_t thai_symbols[] = {
	"\340\271\220", "\340\271\221", "\340\271\222", "\340\271\223", "\340\271\224", "\340\271\225", "\340\271\226", "\340\271\227", "\340\271\230", "\340\271\231"
};
static const struct list_counter_style lcs_thai = {
	"thai",
	calc_numeric_system,
	NULL,
	thai_symbols,
	NULL,
	(sizeof(thai_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};

static const symbol_t tibetan_symbols[] = {
	"\340\274\240", "\340\274\241", "\340\274\242", "\340\274\243", "\340\274\244", "\340\274\245", "\340\274\246", "\340\274\247", "\340\274\250", "\340\274\251"
};
static const struct list_counter_style lcs_tibetan = {
	"tibetan",
	calc_numeric_system,
	NULL,
	tibetan_symbols,
	NULL,
	(sizeof(tibetan_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	NULL
};

static const symbol_t cjk_earthly_branch_symbols[] = {
	"\345\255\220", "\344\270\221", "\345\257\205", "\345\215\257", "\350\276\260", "\345\267\263", "\345\215\210", "\346\234\252", "\347\224\263", "\351\205\211", "\346\210\214", "\344\272\245"
};
static struct list_counter_style lcs_cjk_earthly_branch = {
	"cjk-earthly-branch",
	calc_alphabet_system,
	&lcs_decimal,
	cjk_earthly_branch_symbols,
	NULL,
	(sizeof(cjk_earthly_branch_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	"\343\200\201"
};

static const symbol_t cjk_heavenly_stem_symbols[] = {
	"\347\224\262", "\344\271\231", "\344\270\231", "\344\270\201", "\346\210\212", "\345\267\261", "\345\272\232", "\350\276\233", "\345\243\254", "\347\231\270"
};
static struct list_counter_style lcs_cjk_heavenly_stem = {
	"cjk-heavenly-stem",
	calc_alphabet_system,
	&lcs_decimal,
	cjk_heavenly_stem_symbols,
	NULL,
	(sizeof(cjk_heavenly_stem_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	"\343\200\201"
};

static const symbol_t hiragana_symbols[] = {
	"\343\201\202", "\343\201\204", "\343\201\206", "\343\201\210", "\343\201\212", "\343\201\213", "\343\201\215", "\343\201\217", "\343\201\221", "\343\201\223", "\343\201\225", "\343\201\227", "\343\201\231", "\343\201\233", "\343\201\235", "\343\201\237", "\343\201\241", "\343\201\244", "\343\201\246", "\343\201\250", "\343\201\252", "\343\201\253", "\343\201\254", "\343\201\255", "\343\201\256", "\343\201\257", "\343\201\262", "\343\201\265", "\343\201\270", "\343\201\273", "\343\201\276", "\343\201\277", "\343\202\200", "\343\202\201", "\343\202\202", "\343\202\204", "\343\202\206", "\343\202\210", "\343\202\211", "\343\202\212", "\343\202\213", "\343\202\214", "\343\202\215", "\343\202\217", "\343\202\220", "\343\202\221", "\343\202\222", "\343\202\223"
};
static struct list_counter_style lcs_hiragana = {
	"hiragana",
	calc_alphabet_system,
	&lcs_decimal,
	hiragana_symbols,
	NULL,
	(sizeof(hiragana_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	"\343\200\201"
};

static const symbol_t hiragana_iroha_symbols[] = {
	"\343\201\204", "\343\202\215", "\343\201\257", "\343\201\253", "\343\201\273", "\343\201\270", "\343\201\250", "\343\201\241", "\343\202\212", "\343\201\254", "\343\202\213", "\343\202\222", "\343\202\217", "\343\201\213", "\343\202\210", "\343\201\237", "\343\202\214", "\343\201\235", "\343\201\244", "\343\201\255", "\343\201\252", "\343\202\211", "\343\202\200", "\343\201\206", "\343\202\220", "\343\201\256", "\343\201\212", "\343\201\217", "\343\202\204", "\343\201\276", "\343\201\221", "\343\201\265", "\343\201\223", "\343\201\210", "\343\201\246", "\343\201\202", "\343\201\225", "\343\201\215", "\343\202\206", "\343\202\201", "\343\201\277", "\343\201\227", "\343\202\221", "\343\201\262", "\343\202\202", "\343\201\233", "\343\201\231"
};
static struct list_counter_style lcs_hiragana_iroha = {
	"hiragana-iroha",
	calc_alphabet_system,
	&lcs_decimal,
	hiragana_iroha_symbols,
	NULL,
	(sizeof(hiragana_iroha_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	"\343\200\201"
};

static const symbol_t katakana_symbols[] = {
	"\343\202\242", "\343\202\244", "\343\202\246", "\343\202\250", "\343\202\252", "\343\202\253", "\343\202\255", "\343\202\257", "\343\202\261", "\343\202\263", "\343\202\265", "\343\202\267", "\343\202\271", "\343\202\273", "\343\202\275", "\343\202\277", "\343\203\201", "\343\203\204", "\343\203\206", "\343\203\210", "\343\203\212", "\343\203\213", "\343\203\214", "\343\203\215", "\343\203\216", "\343\203\217", "\343\203\222", "\343\203\225", "\343\203\230", "\343\203\233", "\343\203\236", "\343\203\237", "\343\203\240", "\343\203\241", "\343\203\242", "\343\203\244", "\343\203\246", "\343\203\250", "\343\203\251", "\343\203\252", "\343\203\253", "\343\203\254", "\343\203\255", "\343\203\257", "\343\203\260", "\343\203\261", "\343\203\262", "\343\203\263"
};
static struct list_counter_style lcs_katakana = {
	"katakana",
	calc_alphabet_system,
	&lcs_decimal,
	katakana_symbols,
	NULL,
	(sizeof(katakana_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	"\343\200\201"
};

static const symbol_t katakana_iroha_symbols[] = {
	"\343\202\244", "\343\203\255", "\343\203\217", "\343\203\213", "\343\203\233", "\343\203\230", "\343\203\210", "\343\203\201", "\343\203\252", "\343\203\214", "\343\203\253", "\343\203\262", "\343\203\257", "\343\202\253", "\343\203\250", "\343\202\277", "\343\203\254", "\343\202\275", "\343\203\204", "\343\203\215", "\343\203\212", "\343\203\251", "\343\203\240", "\343\202\246", "\343\203\260", "\343\203\216", "\343\202\252", "\343\202\257", "\343\203\244", "\343\203\236", "\343\202\261", "\343\203\225", "\343\202\263", "\343\202\250", "\343\203\206", "\343\202\242", "\343\202\265", "\343\202\255", "\343\203\246", "\343\203\241", "\343\203\237", "\343\202\267", "\343\203\261", "\343\203\222", "\343\203\242", "\343\202\273", "\343\202\271"
};
static struct list_counter_style lcs_katakana_iroha = {
	"katakana-iroha",
	calc_alphabet_system,
	&lcs_decimal,
	katakana_iroha_symbols,
	NULL,
	(sizeof(katakana_iroha_symbols) / SYMBOL_SIZE),
	{ 0, 0 },
	{ 0, { 0 } },
	{ NULL, NULL },
	NULL,
	"\343\200\201"
};

/**
 * weights suitable for the five complex addative styles
 */
static const int complex_counter_weights[] = {
	9000, 8000, 7000, 6000, 5000, 4000, 3000, 2000, 1000,
	900,  800,  700,  600,  500,  400,  300,  200,  100,
	90,   80,   70,   60,   50,   40,   30,   20,   10,
	9,    8,    7,    6,    5,    4,    3,    2,    1,    0
};
static const symbol_t japanese_informal_symbols[] = {
	"\344\271\235\345\215\203", "\345\205\253\345\215\203", "\344\270\203\345\215\203", "\345\205\255\345\215\203", "\344\272\224\345\215\203", "\345\233\233\345\215\203", "\344\270\211\345\215\203", "\344\272\214\345\215\203", "\345\215\203",
	"\344\271\235\347\231\276", "\345\205\253\347\231\276", "\344\270\203\347\231\276", "\345\205\255\347\231\276", "\344\272\224\347\231\276", "\345\233\233\347\231\276", "\344\270\211\347\231\276", "\344\272\214\347\231\276", "\347\231\276",
	"\344\271\235\345\215\201", "\345\205\253\345\215\201", "\344\270\203\345\215\201", "\345\205\255\345\215\201", "\344\272\224\345\215\201", "\345\233\233\345\215\201", "\344\270\211\345\215\201", "\344\272\214\345\215\201", "\345\215\201",
	"\344\271\235", "\345\205\253", "\344\270\203", "\345\205\255", "\344\272\224", "\345\233\233", "\344\270\211", "\344\272\214", "\344\270\200", "\343\200\207",
};
static const struct list_counter_style lcs_japanese_informal = {
	"japanese-informal",
	calc_additive_system,
	&lcs_cjk_decimal,
	japanese_informal_symbols,
	complex_counter_weights,
	(sizeof(japanese_informal_symbols) / SYMBOL_SIZE),
	{ -9999, 9999 },
	{ 0, { 0 } },
	{ "\343\203\236\343\202\244\343\203\212\343\202\271", NULL },
	NULL,
	"\xE3\x80\x81"
};

static const symbol_t japanese_formal_symbols[] = {
	"\344\271\235\351\230\241", "\345\205\253\351\230\241", "\344\270\203\351\230\241", "\345\205\255\351\230\241", "\344\274\215\351\230\241", "\345\233\233\351\230\241", "\345\217\202\351\230\241", "\345\274\220\351\230\241", "\345\243\261\351\230\241",
	"\344\271\235\347\231\276", "\345\205\253\347\231\276", "\344\270\203\347\231\276", "\345\205\255\347\231\276", "\344\274\215\347\231\276", "\345\233\233\347\231\276", "\345\217\202\347\231\276", "\345\274\220\347\231\276", "\345\243\261\347\231\276",
	"\344\271\235\346\213\276", "\345\205\253\346\213\276", "\344\270\203\346\213\276", "\345\205\255\346\213\276", "\344\274\215\346\213\276", "\345\233\233\346\213\276", "\345\217\202\346\213\276", "\345\274\220\346\213\276", "\345\243\261\346\213\276",
	"\344\271\235", "\345\205\253", "\344\270\203", "\345\205\255", "\344\274\215", "\345\233\233", "\345\217\202", "\345\274\220", "\345\243\261", "\351\233\266",
};
static const struct list_counter_style lcs_japanese_formal = {
	"japanese-formal",
	calc_additive_system,
	&lcs_cjk_decimal,
	japanese_formal_symbols,
	complex_counter_weights,
	(sizeof(japanese_formal_symbols) / SYMBOL_SIZE),
	{ -9999, 9999 },
	{ 0, { 0 } },
	{ "\343\203\236\343\202\244\343\203\212\343\202\271", NULL },
	NULL,
	"\xE3\x80\x81"
};

static const symbol_t korean_hangul_formal_symbols[] = {
	"\352\265\254\354\262\234", "\355\214\224\354\262\234", "\354\271\240\354\262\234", "\354\234\241\354\262\234", "\354\230\244\354\262\234", "\354\202\254\354\262\234", "\354\202\274\354\262\234", "\354\235\264\354\262\234", "\354\235\274\354\262\234",
	"\352\265\254\353\260\261", "\355\214\224\353\260\261", "\354\271\240\353\260\261", "\354\234\241\353\260\261", "\354\230\244\353\260\261", "\354\202\254\353\260\261", "\354\202\274\353\260\261", "\354\235\264\353\260\261", "\354\235\274\353\260\261",
	"\352\265\254\354\213\255", "\355\214\224\354\213\255", "\354\271\240\354\213\255", "\354\234\241\354\213\255", "\354\230\244\354\213\255", "\354\202\254\354\213\255", "\354\202\274\354\213\255", "\354\235\264\354\213\255", "\354\235\274\354\213\255",
	"\352\265\254", "\355\214\224", "\354\271\240", "\354\234\241", "\354\230\244", "\354\202\254", "\354\202\274", "\354\235\264", "\354\235\274", "\354\230\201"
};
static const struct list_counter_style lcs_korean_hangul_formal = {
	"korean-hangul-formal",
	calc_additive_system,
	&lcs_cjk_decimal,
	korean_hangul_formal_symbols,
	complex_counter_weights,
	(sizeof(korean_hangul_formal_symbols) / SYMBOL_SIZE),
	{ -9999, 9999 },
	{ 0, { 0 } },
	{ "\xEB\xA7\x88\xEC\x9D\xB4\xEB\x84\x88\xEC\x8A\xA4 ", NULL },
	NULL,
	", "
};

static const symbol_t korean_hanja_informal_symbols[] = {
	"\344\271\235\345\215\203", "\345\205\253\345\215\203", "\344\270\203\345\215\203", "\345\205\255\345\215\203", "\344\272\224\345\215\203", "\345\233\233\345\215\203", "\344\270\211\345\215\203", "\344\272\214\345\215\203", "\345\215\203",
	"\344\271\235\347\231\276", "\345\205\253\347\231\276", "\344\270\203\347\231\276", "\345\205\255\347\231\276", "\344\272\224\347\231\276", "\345\233\233\347\231\276", "\344\270\211\347\231\276", "\344\272\214\347\231\276", "\347\231\276",
	"\344\271\235\345\215\201", "\345\205\253\345\215\201", "\344\270\203\345\215\201", "\345\205\255\345\215\201", "\344\272\224\345\215\201", "\345\233\233\345\215\201", "\344\270\211\345\215\201", "\344\272\214\345\215\201", "\345\215\201",
	"\344\271\235", "\345\205\253", "\344\270\203", "\345\205\255", "\344\272\224", "\345\233\233", "\344\270\211", "\344\272\214", "\344\270\200", "\351\233\266"
};
static const struct list_counter_style lcs_korean_hanja_informal = {
	"korean-hanja-informal",
	calc_additive_system,
	&lcs_cjk_decimal,
	korean_hanja_informal_symbols,
	complex_counter_weights,
	(sizeof(korean_hanja_informal_symbols) / SYMBOL_SIZE),
	{ -9999, 9999 },
	{ 0, { 0 } },
	{ "\xEB\xA7\x88\xEC\x9D\xB4\xEB\x84\x88\xEC\x8A\xA4 ", NULL },
	NULL,
	", "
};

static const symbol_t korean_hanja_formal_symbols[] = {
	"\344\271\235\344\273\237", "\345\205\253\344\273\237", "\344\270\203\344\273\237", "\345\205\255\344\273\237", "\344\272\224\344\273\237", "\345\233\233\344\273\237", "\345\217\203\344\273\237", "\350\262\263\344\273\237", "\345\243\271\344\273\237",
	"\344\271\235\347\231\276", "\345\205\253\347\231\276", "\344\270\203\347\231\276", "\345\205\255\347\231\276", "\344\272\224\347\231\276", "\345\233\233\347\231\276", "\345\217\203\347\231\276", "\350\262\263\347\231\276", "\345\243\271\347\231\276",
	"\344\271\235\346\213\276", "\345\205\253\346\213\276", "\344\270\203\346\213\276", "\345\205\255\346\213\276", "\344\272\224\346\213\276", "\345\233\233\346\213\276", "\345\217\203\346\213\276", "\350\262\263\346\213\276", "\345\243\271\346\213\276",
	"\344\271\235", "\345\205\253", "\344\270\203", "\345\205\255", "\344\272\224", "\345\233\233", "\345\217\203", "\350\262\263", "\345\243\271", "\351\233\266"
};
static const struct list_counter_style lcs_korean_hanja_formal = {
	"korean-hanja-formal",
	calc_additive_system,
	&lcs_cjk_decimal,
	korean_hanja_formal_symbols,
	complex_counter_weights,
	(sizeof(korean_hanja_formal_symbols) / SYMBOL_SIZE),
	{ -9999, 9999 },
	{ 0, { 0 } },
	{ "\xEB\xA7\x88\xEC\x9D\xB4\xEB\x84\x88\xEC\x8A\xA4 ", NULL },
	NULL,
	", "
};



static const struct list_counter_style *
counter_style_from_computed_style(const css_computed_style *style)
{
	switch (get_list_style_type(style)) {
	case CSS_LIST_STYLE_TYPE_DISC:
		return &lcs_disc;
	case CSS_LIST_STYLE_TYPE_CIRCLE:
		return &lcs_circle;
	case CSS_LIST_STYLE_TYPE_SQUARE:
		return &lcs_square;
	case CSS_LIST_STYLE_TYPE_DECIMAL:
		return &lcs_decimal;
	case CSS_LIST_STYLE_TYPE_DECIMAL_LEADING_ZERO:
		return &lcs_decimal_leading_zero;
	case CSS_LIST_STYLE_TYPE_LOWER_ROMAN:
		return &lcs_lower_roman;
	case CSS_LIST_STYLE_TYPE_UPPER_ROMAN:
		return &lcs_upper_roman;
	case CSS_LIST_STYLE_TYPE_LOWER_GREEK:
		return &lcs_lower_greek;
	case CSS_LIST_STYLE_TYPE_LOWER_ALPHA:
	case CSS_LIST_STYLE_TYPE_LOWER_LATIN:
		return &lcs_lower_alpha;
	case CSS_LIST_STYLE_TYPE_UPPER_ALPHA:
	case CSS_LIST_STYLE_TYPE_UPPER_LATIN:
		return &lcs_upper_alpha;
	case CSS_LIST_STYLE_TYPE_UPPER_ARMENIAN:
	case CSS_LIST_STYLE_TYPE_ARMENIAN:
		return &lcs_upper_armenian;
	case CSS_LIST_STYLE_TYPE_GEORGIAN:
		return &lcs_georgian;
	case CSS_LIST_STYLE_TYPE_NONE:
		return NULL;
	case CSS_LIST_STYLE_TYPE_BINARY:
		return &lcs_binary;
	case CSS_LIST_STYLE_TYPE_OCTAL:
		return &lcs_octal;
	case CSS_LIST_STYLE_TYPE_LOWER_HEXADECIMAL:
		return &lcs_lower_hexadecimal;
	case CSS_LIST_STYLE_TYPE_UPPER_HEXADECIMAL:
		return &lcs_upper_hexadecimal;
	case CSS_LIST_STYLE_TYPE_ARABIC_INDIC:
		return &lcs_arabic_indic;
	case CSS_LIST_STYLE_TYPE_LOWER_ARMENIAN:
		return &lcs_lower_armenian;
	case CSS_LIST_STYLE_TYPE_BENGALI:
		return &lcs_bengali;
	case CSS_LIST_STYLE_TYPE_CAMBODIAN:
	case CSS_LIST_STYLE_TYPE_KHMER:
		return &lcs_cambodian;
	case CSS_LIST_STYLE_TYPE_CJK_DECIMAL:
		return &lcs_cjk_decimal;
	case CSS_LIST_STYLE_TYPE_DEVANAGARI:
		return &lcs_devanagari;
	case CSS_LIST_STYLE_TYPE_GUJARATI:
		return &lcs_gujarati;
	case CSS_LIST_STYLE_TYPE_GURMUKHI:
		return &lcs_gurmukhi;
	case CSS_LIST_STYLE_TYPE_HEBREW:
		return &lcs_hebrew;
	case CSS_LIST_STYLE_TYPE_KANNADA:
		return &lcs_kannada;
	case CSS_LIST_STYLE_TYPE_LAO:
		return &lcs_lao;
	case CSS_LIST_STYLE_TYPE_MALAYALAM:
		return &lcs_malayalam;
	case CSS_LIST_STYLE_TYPE_MONGOLIAN:
		return &lcs_mongolian;
	case CSS_LIST_STYLE_TYPE_MYANMAR:
		return &lcs_myanmar;
	case CSS_LIST_STYLE_TYPE_ORIYA:
		return &lcs_oriya;
	case CSS_LIST_STYLE_TYPE_PERSIAN:
		return &lcs_persian;
	case CSS_LIST_STYLE_TYPE_TAMIL:
		return &lcs_tamil;
	case CSS_LIST_STYLE_TYPE_TELUGU:
		return &lcs_telugu;
	case CSS_LIST_STYLE_TYPE_THAI:
		return &lcs_thai;
	case CSS_LIST_STYLE_TYPE_TIBETAN:
		return &lcs_tibetan;
	case CSS_LIST_STYLE_TYPE_CJK_EARTHLY_BRANCH:
		return &lcs_cjk_earthly_branch;
	case CSS_LIST_STYLE_TYPE_CJK_HEAVENLY_STEM:
		return &lcs_cjk_heavenly_stem;
	case CSS_LIST_STYLE_TYPE_HIAGANA:
		return &lcs_hiragana;
	case CSS_LIST_STYLE_TYPE_HIAGANA_IROHA:
		return &lcs_hiragana_iroha;
	case CSS_LIST_STYLE_TYPE_KATAKANA:
		return &lcs_katakana;
	case CSS_LIST_STYLE_TYPE_KATAKANA_IROHA:
		return &lcs_katakana_iroha;
	case CSS_LIST_STYLE_TYPE_JAPANESE_INFORMAL:
		return &lcs_japanese_informal;
	case CSS_LIST_STYLE_TYPE_JAPANESE_FORMAL:
		return &lcs_japanese_formal;
	case CSS_LIST_STYLE_TYPE_KOREAN_HANGUL_FORMAL:
		return &lcs_korean_hangul_formal;
	case CSS_LIST_STYLE_TYPE_KOREAN_HANJA_INFORMAL:
		return &lcs_korean_hanja_informal;
	case CSS_LIST_STYLE_TYPE_KOREAN_HANJA_FORMAL:
		return &lcs_korean_hanja_formal;
	}
	return NULL;
}


/* exported interface defined in select.h */
css_error css_computed_format_list_style(
		const css_computed_style *style,
		int value,
		char *buffer,
		size_t buffer_length,
		size_t *format_length)
{
	css_error res = CSS_INVALID;
	const struct list_counter_style *cstyle;
	uint8_t aval[20];
	struct numeric nval = { aval, sizeof(aval), 0, false };


	cstyle = counter_style_from_computed_style(style);
	while (cstyle != NULL) {
		res = cstyle->system(value, cstyle, &nval);

		if ((res == CSS_OK) &&
		    (nval.used < nval.len)) {
			/* system sucessfully generated numeric values */
			*format_length = nval_to_symbols(&nval,
							 cstyle,
							 buffer,
							 buffer_length);
			break;
		}

		res = CSS_INVALID;
		cstyle = cstyle->fallback;
	}

	return res;
}

